apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: shuffle
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Shuffle Security Orchestration Platform
    version: 1.0.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.0"
    description:
      tagline: Open-source SOAR platform for security automation
      detailed: |
        Shuffle is an open-source Security Orchestration, Automation and Response (SOAR) platform 
        that helps security teams automate repetitive tasks and connect different security tools.
        
        This deployment creates a highly available Docker Swarm cluster with automatic NFS configuration,
        OpenSearch for data storage, and load-balanced frontend/backend services.
  ui:
    input:
      variables:
        project_id:
          name: project_id
          title: Project ID
          invisible: true

        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Deployment name
          invisible: true

        source_image:
          name: source_image
          title: Source Image
          enumValueLabels:
            - label: shuffle-ubuntu2404-x86-64-20251208
              value: projects/shuffle-public/global/images/shuffle-ubuntu2404-x86-64-20251208
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
            zoneProperty: zone

        zone:
          name: zone
          title: Zone
          tooltip: The zone where Shuffle cluster will be deployed. Choose a zone close to your users for best performance. If more than one node is deployed, they will be distributed across multiple zones within the selected region.
          xGoogleProperty:
            type: ET_GCE_ZONE

        node_count:
          name: node_count
          title: Number of cluster nodes
          tooltip: Total number of nodes in the Shuffle cluster. Single node for testing, 3+ nodes for production HA.
          min: 1
          max: 10
          section: cluster_configuration

        machine_type:
          name: machine_type
          title: Machine type
          tooltip: Machine type for cluster nodes. e2-standard-2 (2 vCPUs, 8GB RAM) recommended for single node, e2-standard-4 for multi-node.
          section: cluster_configuration
          xGoogleProperty:
            type: ET_GCE_MACHINE_TYPE
            zoneProperty: zone

        boot_disk_type:
          name: boot_disk_type
          title: Boot disk type
          tooltip: Type of persistent disk for boot volume
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_TYPE
            zoneProperty: zone

        boot_disk_size:
          name: boot_disk_size
          title: Boot disk size in GB
          tooltip: Size of the boot disk for each node
          min: 120
          max: 1000
          section: boot_disk
          xGoogleProperty:
            type: ET_GCE_DISK_SIZE
            gceDiskSize:
              diskTypeVariable: boot_disk_type

        external_access_cidrs:
          name: external_access_cidrs
          title: Source IP ranges for Shuffle UI access
          tooltip: 'Comma-separated CIDR ranges allowed to access Shuffle UI (port 3001). Use CIDR notation. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0'
          section: networking

        enable_ssh:
          name: enable_ssh
          title: Enable SSH access
          tooltip: Allow SSH access to cluster nodes
          section: networking

        ssh_source_ranges:
          name: ssh_source_ranges
          title: Source IP ranges for SSH access
          tooltip: 'Comma-separated CIDR ranges allowed for SSH access. Use CIDR notation. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>'
          placeholder: '0.0.0.0/0'
          section: networking

        enable_cloud_logging:
          name: enable_cloud_logging
          title: Enable Cloud Logging
          tooltip: 'Cloud Logging allows you to store, search, analyze, monitor, and alert on log data and events. <a href="https://cloud.google.com/logging/">Learn more</a>'
          section: google_cloud_operations

        enable_cloud_monitoring:
          name: enable_cloud_monitoring
          title: Enable Cloud Monitoring
          tooltip: 'Cloud Monitoring provides visibility into the performance, uptime, and overall health of cloud-powered applications. <a href="https://cloud.google.com/monitoring/">Learn more</a>'
          section: google_cloud_operations

        environment:
          name: environment
          title: Environment
          tooltip: Environment label for resource organization
          section: google_cloud_operations
          level: 1
          enumValueLabels:
            - label: Production
              value: production
            - label: Staging
              value: staging
            - label: Development
              value: dev

      sections:
        - name: cluster_configuration
          title: Cluster Configuration
          tooltip: Configure the size and capacity of your Shuffle cluster

        - name: boot_disk
          title: Boot Disk
          tooltip: Each instance requires a disk to boot from

        - name: networking
          title: Networking
          tooltip: Configure network access and firewall rules

        - name: google_cloud_operations
          title: Google Cloud Operations
          tooltip: Monitoring and management for services, containers, applications, and infrastructure

    runtime:
      outputMessage: |
        Deployment of Shuffle Security Orchestration Platform is complete!

        Please wait a few minutes for all services to fully initialize.

      suggestedActions:
        - heading: Access Shuffle Web Interface
          description: '<p>The Shuffle frontend URL will be available in the <strong>Outputs</strong> section once deployment is complete.</p><p>Access it at: <strong>shuffle_frontend_url</strong> (port 3001)</p>'

        - heading: SSH into primary manager node
          description: '<p>Connect to your primary manager node using:</p><code>gcloud compute ssh &lt;INSTANCE_NAME&gt; --zone=&lt;ZONE&gt;</code><p><em>Replace &lt;INSTANCE_NAME&gt; and &lt;ZONE&gt; with values from the Outputs section.</em></p>'

        - heading: View Docker services
          description: '<p>Once connected via SSH, check the status of all Shuffle services:</p><code>sudo docker stack services shuffle</code>'

        - heading: View service logs
          description: '<p>To troubleshoot or monitor a specific service:</p><code>sudo docker service logs shuffle_&lt;service-name&gt;</code><p><em>Example: <code>sudo docker service logs shuffle_backend</code></em></p>'

  requirements:
    services:
      - compute.googleapis.com
      - logging.googleapis.com
      - monitoring.googleapis.com

    roles:
      - level: Project
        roles:
          - roles/compute.instanceAdmin.v1
          - roles/compute.networkAdmin
          - roles/compute.securityAdmin
          - roles/iam.serviceAccountUser